# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hello_prisma
volumes:
  db_data: ~
